version: '3'
services:
  web:
    container_name: daikin-web
    restart: unless-stopped
    image: ehjortberg/daikin-web:latest
    ports:
      - "8000:80"
    environment:
      IPADDR: 192.168.1.11 
